### PR TITLE
Several bug fixes and improvements of `SmartNodeSelector`

### LINKED ISSUE #97: SmartNodeSelector : Bugs
Bugs:
- [x] Empty suggestions list remains open when using `*` wildcard and suggestions list timer is set to 0s
- [x] Typo in tag css class name
- [x] Text width not always calculated correctly
- [x] Fixed font size set 
- [x] Placeholder not applied

### LINKED ISSUE #149: `SmartNodeSelector` improvement suggestions
- [x] Possible to search on description as well, not necessarily need to know the node/vector name.
- [X] Change from red color on X for removing a selection to same color as for the large X that removes all selections.
- [x] Export data types and TreeData (for VectorSelector)

### LINKED ISSUE #186: Possible bug in the `SmartNodeSelector`
I am trying to use the SmartNodeSelector for a plugin that has a tab-based visualisation. 
image

The first time I open the tab containing the SmartNodeSelector everything works as expected. However if I switch to another tab before returning to the tab with the SmartNodeSelector I get an error when clicking in the SmartNodeSelector see error below:

image

I have to admit, I am not sure if this is related to an error in my setup or if it is related to the SmartNodeSelector.. but I am stuck

### LINKED ISSUE #188: `SmartNodeSelector` issues after testing
I made three observations while testing the latest changes to the `SmartNodeSelector` #178 (not released)

- I no longer get any update of selectedNodes while using the arrows to switch between nodes
- switching between nodes using the arrows is much slower than it used to be.. sometimes takes more than 10 seconds
- The placeholder text is cut off in half  
image
 

Also (as a side note)
I am trying to use the `SmartNodeSelector` for strings that tend to get very long. I therefore would love it if #132 or another solution could be prioritised 😉 
image

----
Issues:
- [x] `selectedNodes` not updating when using the browse buttons / not calling update function
- [x] Placeholder text cut off when too long

### PR DESCRIPTION
**Pull request by rubenthoms**
- Feature: OR operator in nodes (beta)
- Bug fix: Placeholder not applied
- Bug fix: Text width not calculated correctly initially
- Feature: Case-insensitive search and apply (optional feature)
- Feature: Export of data types
- Feature: Search on descriptions
- Bug fix: Clicking enter while node editing not finished jumped to next node (if available)
- Improved and bug fixed: Arrow navigation within node input field
- Feature: Tab navigation
- Feature: End/Home navigation
- Improved visual feedback
- Ctrl+Space always opens all suggestions
- Bug fix: Incorrect positioning when scrolling
- Bug fix: Minus was not allowed in node names

Closes #149.
Closes #97.
Fixes #186.
Closes #188.
Addresses #128.

### CODE REVIEW

**Review by jorgenherje — APPROVED** [review]
Really nice features and fixes! 👍

Tested and verified!

**Review by jorgenherje — CHANGES_REQUESTED** [review]
Tested and found some issues.

Testing with usage in VectorSelector (local build) in webviz-subsurface plugin.
**Note:** `VectorSelector` in `wsc` must be updated with `showAllSuggestions` prop


**Issues:**
* Scrolling in suggestions not working when Ctrl+space. If exiting the node edit and entering again, the scroll works. 
* When Ctrl+space shows all suggestions, the `showAllSuggestions` setting remains active when re-entering node editing. I.e. when entering node, matching suggestions are shown in list. When Ctrl+space is entered all suggestions are shown. If one exit (push outside of the editing node in GUI) and enter the node edit again, all suggestions are still shown.

**Review by jorgenherje — CHANGES_REQUESTED** [review]
Tested and found some issues:

* When entering node level, the filtered search removes non-matching suggestions, but then they reappear after a fraction of a second (without pushing Ctrl+space):
MicrosoftTeams-image
* The suggestions does not scroll to active/marked suggestion:
image

File: react/src/lib/components/SmartNodeSelector/components/SmartNodeSelectorComponent.tsx [hunk 1]
```diff
@@ -1743,6 +1746,7 @@ export default class SmartNodeSelectorComponent extends Component<SmartNodeSelec
 
         return (
             <div id={id} ref={this.ref}>
+                {this.debugOutput()}
```
Comment (jorgenherje) [inline react/src/lib/components/SmartNodeSelector/components/SmartNodeSelectorComponent.tsx:1749]: Remove this line

**Review by jorgenherje — CHANGES_REQUESTED** [review]
Tested and found issues:

* Ctrl+space stopped working?
* Remove debug code

**Review by jorgenherje — APPROVED** [review]
Tested functionality and reviewed code changes. Really nice features! 👍
